pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-kaniko
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.16.0-debug
      imagePullPolicy: Always
      command: ["sleep"]
      args: ["99d"]
    - name: git
      image: alpine/git
      command: ["sleep"]
      args: ["99d"]
"""
    }
  }

  environment {
    ECR_REGISTRY = "9611534434107.dkr.ecr.us-west-2.amazonaws.com"
    IMAGE_NAME   = "app"
    IMAGE_TAG    = "v1.0.${BUILD_NUMBER}"

    COMMIT_EMAIL = "jenkins@localhost"
    COMMIT_NAME  = "jenkins"

    # Repository where values.yaml will be updated
    GIT_REPO     = "https://github.com/justpragmaticoder/goit-devops-hw.git"
    GIT_BRANCH   = "main"
  }

  stages {

    stage('Clone Source Repository') {
      steps {
        container('git') {
          withCredentials([usernamePassword(credentialsId: 'github-token', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PAT')]) {
            sh '''
              git clone -b lesson-8-9 https://$GIT_USERNAME:$GIT_PAT@github.com/justpragmaticoder/goit-devops-hw.git source-repo
            '''
          }
        }
      }
    }

    stage('Build & Push Docker Image') {
      steps {
        container('kaniko') {
          sh '''
            /kaniko/executor \
              --context $(pwd)/source-repo/django \
              --dockerfile $(pwd)/source-repo/django/Dockerfile \
              --destination=$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG \
              --cache=true \
              --insecure \
              --skip-tls-verify
          '''
        }
      }
    }

    stage('Update Helm Chart Tag') {
      steps {
        container('git') {
          withCredentials([usernamePassword(credentialsId: 'github-token', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PAT')]) {
            sh '''
              git clone -b $GIT_BRANCH $GIT_REPO helm-repo
              cd helm-repo/django-chart

              sed -i "s/tag: .*/tag: $IMAGE_TAG/" values.yaml

              git config user.email "$COMMIT_EMAIL"
              git config user.name "$COMMIT_NAME"

              git add values.yaml
              git commit -m "Update image tag to $IMAGE_TAG"
              git push origin $GIT_BRANCH
            '''
          }
        }
      }
    }

  }
}